version: '3.9'
services:
  #######
  # Verifier Backend
  #######
  plurality-verifier-be:
    container_name: plurality-verifier-be
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    environment:
      PORT: 5000
      TWITTER_CALLBACK_URL: ${TWITTER_CALLBACK_URL}
      TWITTER_CLIENT_ID: ${TWITTER_CLIENT_ID}
      TWITTER_CLIENT_SECRET: ${TWITTER_CLIENT_SECRET}
      SIGNER_PRIVATE_KEY: ${VERIFIER_WALLET_PRIVATE_KEY}
      VERIFIER_UI_URL: ${VERIFIER_UI_URL}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.plurality-verifier-be-route.service=plurality-verifier-be-service'
      - 'traefik.http.routers.plurality-verifier-be-route.entrypoints=websecure'
      - 'traefik.http.routers.plurality-verifier-be-route.tls.certresolver=myresolver'
      - 'traefik.http.routers.plurality-verifier-be-route.rule=Host(`plurality-backend.mmssec.com`)'
      - 'traefik.http.services.plurality-verifier-be-service.loadbalancer.server.port=5000'
    restart: always
    networks:
      - plurality-verifier-network
  #######
  # Verifier UI
  #######
  plurality-verifier-ui:
    container_name: plurality-verifier-ui
    build:
      context: ./packages/site
      dockerfile: Dockerfile
    command: bash -c "sudo yarn deploy"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.plurality-verifier-ui-route.service=plurality-verifier-ui-service'
      - 'traefik.http.routers.plurality-verifier-ui-route.entrypoints=websecure'
      - 'traefik.http.routers.plurality-verifier-ui-route.tls.certresolver=myresolver'
      - 'traefik.http.routers.plurality-verifier-ui-route.rule=Host(`plurality.westeurope.cloudapp.azure.com`)'
      - 'traefik.http.services.plurality-verifier-ui-service.loadbalancer.server.port=8000'
    restart: always
    networks:
      - plurality-verifier-network
  #######
  # Ingress
  #######
  plurality-traefik-proxy:
    container_name: plurality-traefik-proxy
    image: traefik
    restart: always
    ports:
      - '443:443'
      - '80:80'
    command:
      - '--api=true'
      - '--api.insecure=true'
      - '--api.dashboard=true'
      - '--log.level=DEBUG'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.file.filename=/dynamic_config.yml'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      # TESTING
      - '--certificatesresolvers.myresolver.acme.email=plurality.web3@gmail.com'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    volumes:
      - './traefik/letsencrypt:/letsencrypt'
      - './traefik/config/dynamic_config.yml:/dynamic_config.yml'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - plurality-verifier-network
    depends_on:
      - plurality-verifier-ui

networks:
  plurality-verifier-network:
